project:
  type: website
  output-dir: docs
  
website:
  title: "Daisy Nguyen"
  navbar:
    left:
      - href: index.qmd
        text: home
      
      - href: research.qmd
        text: research
      
      - text: projects
        menu: 
          - href: sql_project.qmd
            text: SQL project
          - href: text_analysis_project.qmd
            text: text analysis project
          - href: Rpackage.qmd
            text: R package
            
      - href: about.qmd

      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


