project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  favicon: images/icon.png
  title: "Daisy Nguyen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
        
      - text: Projects
        menu: 
          - href: sql_project.qmd
            text: SQL project
          - href: text_analysis_project.qmd
            text: text analysis project
          - href: Rpackage.qmd
            text: R package
            
      - href: capstone.qmd
        text: Capstone Project
 
  page-footer:
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>

format:
  html:
    theme: [yeti, theme.scss]
    toc: true
    code-overflow: wrap

editor: visual

