project:
  type: website
  output-dir: docs
  resources:
    - "data/"
    - "research/images_quantum/"
    - "projects tab/poster.pdf"
    - "images/"
  render:
    - "*.qmd"

website:
  favicon: images/icon.png
  title: "Daisy Nguyen"
  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - text: Projects in R
        menu: 
          - href: "projects tab/sql_project.qmd"
            text: SQL project
          - href: "projects tab/text_analysis_project.qmd"
            text: Text Analysis Project
          - href: "projects tab/Rpackage.qmd"
            text: R package
          - href: "projects tab/poster.qmd"
            text: Differential Privacy Poster
            
            
      - text: Research
        menu: 
          - href: "research/capstone.qmd"
            text: Plasma Physics
          - href: "research/quantum.qmd"
            text: Single Photon Optics
          - href: "research/common_emitter_amplifier.qmd"
            text: Common-Emitter Amplifier
            
      - text: Math Concepts   
        menu:
          - href: linear_al.qmd
            text: Linear Algebra
      
 
  page-footer:
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>

format:
  html:
    theme: [yeti, theme.scss]
    toc: true
    code-overflow: wrap

editor: visual

