---
title: "Differential Privacy Poster"
author: Daisy Nguyen
---

## Poster on Cynthia Dwork's paper on Differential Privacy (2006)


<iframe src="poster.pdf" width="100%" height="900">

</iframe>

### Overview

The paper was written by Cynthia Dwork in 2006 while she was a researcher at the Microsoft Research. It lays out the mathematical framework and foundation of Differential Privacy, which was motivated by the Dalenius's idea about privacy. In 1977, the father of privacy in statistical databases claimed that "nothing about an individual should be learnable from a database that cannot be learned without access to the database." In other words, performing statistical analysis on a database should not disclose any information about any individual whether or not they are in the database. 

Dwork wanted to show that this type of absolute privacy cannot be achieved due to auxiliary information, and proposed differential privacy as a new privacy measure that shifts the attention from absolute to relative guarantees about information disclosures. The underlying concept here is that privacy-preserving statistical database should allow users to learn properties of a population as a whole while leaving information about the individuals intact, and any given disclosure regarding an individual is just as likely whether or not they participate in the database.

Specifically, she pointed out that the previous definition of privacy goal, one which Dalenius used, set us up for failure. She asked what we mean by preserving privacy and redirected the goal of privacy-preserving database: the goal is not to have an absolute disclosure, but to minimize the increased risk to an individual's privacy incurred by participating in a database. A user interacts with a database should not be able to tell whether or not an individual participates in the database. 

### Problem with Absolute Privacy

The problem with Dalenius's idea of absolute privacy is that, consider a database that tells the users the average heights of women of different nationalities. And suppose that one's exact height is a highly sensitive piece of information, and revealing the exact height of any individual is a privacy breach (just like your Social Security Number). An adversary, someone with the incentive to preach the database, has access to the database and the auxiliary information that "Terry Gross is two inches shorter than the average Lithuanian woman." They then can learn Terry Gross's exact height. Meanwhile, someone that has access to the auxiliary information but not the database does not know anything about Terry Gross' actual height. Thus, in this scenario, having access to a statistical database enable an adversary to learn about a specific individual that could not be learned without access to the database. Meanwhile, someone that has access to the auxiliary information but not the database does not know anything about Terry Gross' actual height. 


### Past attempts in privacy for statistical database

Early attempts at protecting individual's privacy in this field include forbidding queries about specific individuals; determining by analysis if a set of queries will cause disclosure; releasing only a subset of the database; or adding random noise to the query responses. But none of these works for different reasons. The first one, like we saw in the height example, fails because an adversary does not need to ask specifically what Terry Gross's height is, and yet is still able to gain information on Terry. The second attempt fails because it is simple computationally unfeasible, while the third one penalizes individuals that are present in the subsample. Lastly, random noise cannot be implemented naively because it can easily be defeated. Instead, differential privacy is built on a randomized algorithm that is mathematically supported to determine how much noise needed to hide away the individual information. 

### How to achieve Differential Privacy?

Cynthia redefined the notion of privacy to be centered on how the presence or absence of an individual in a database is ambiguous in statistical analyses, rather than focusing on preventing information leakage from database. A randomized algorithm is considered $\epsilon$-differential privacy if for all pairs of databases that differ by at most one element, the query outputs between them are indistinguishable. In other words, the users should not be able to tell whether an element was in the database or not based on the answers that they got for their query. 

To achieve this, we need a randomized algorithm to introduce the noise into the database's answers to queries. But we cannot simply introduce noise in a naive way; instead, we start with defining a parameter known as the L1-sensitivity of the query. This is the maximum difference between the query's answers when a single element is present versus not present in the database. If the sensitivity of the query is high, meaning that the difference when an element is included and not included is high, we will need a large noise to mask the private information of individual data points. 

Once we determine the sensitivity of the query, we can then add appropriately chosen random noise as a function of the query's sensitivity using the Laplace Distribution whose spread is determined by the ratio between the sensitivity and the input privacy budget $\epsilon$. Finally, the randomized algorithm will add random noise sampled from the Laplace Distribution with the calculated spread. This way, it never reveals the actual answer and safely outputs a blurred one that still accurately describes the properties of the whole population.

### Conclusion

The choice of $\epsilon$ in differential privacy determines the tradeoff between data privacy and statistical utility. Therefore, applying this measure to record-level data release or collection requires a very small $\epsilon$ to obtain a meaningful privacy guarantee. As a result, the statistical outputs suffer from the large introduced noise. This problem arises as soon as differential privacy moves outside of the interactive statistical query setting.

This paper really set the ground work for data privacy. According to the author, she hopes that it "democratizes research" and gives opportunities to members of the public the access to highly sensitive data sources to learn about a population as a whole. On the other side, as the concept of differential privacy comes to life, many companies and research institutes also develop differential privacy libraries (Aitsam 2022). These libraries allow users with no background on differential privacy to secure the privacy of the individuals featured in their dataset while being able to release their findings to the public.  



